# install Node.js, install dependencies, and upload the packaged app (as a zip file) to an S3 bucket.
version: 0.2

phases:
  install:
    commands:
      - echo "Installing Node.js 18"
      - curl -sL https://rpm.nodesource.com/setup_18.x | sudo -E bash -
      - sudo yum install -y nodejs
  build:
    commands:
      - echo "Starting the build process"
      - npm install
  post_build:
    commands:
      - echo "Build complete, packaging the app"
      - zip -r app.zip .
      - aws s3 cp app.zip s3://okim-node-app-s3/app.zip

artifacts:
  files:
    - server.js
    - scripts/*
    - appspec.yml
